FlaskApp/models.py
from . import db
from passlib.hash import sha256_crypt
from datetime import datetime


# class Role(db.Model):
#     __tablename__= 'roles'
#     users = db.relationship('User', backref='role')
#     name = db.Column(db.String(64), unique = True)
#     id = db.Column(db.Integer, primary_key= True)

class Project(db.Model):
    __tablename__='projects'
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(50), unique = True, index = True)
    tags = db.Column(db.String(64))
    description = db.Column(db.Text)
    date = db.Column(db.DateTime)
    links = db.Column(db.String(512), nullable = True)
    image_filename = db.Column(db.String(128), default = None, nullable = True)
    image_url = db.Column(db.String(128), default = None, nullable = True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    @staticmethod
    def generate_fake(count=20):
        from random import seed, randint
        import forgery_py

        seed()
        user_count = User.query.count()
        for i in range(count):
            u = User.query.offset(randint(0, user_count - 1)).first()
            p = Project(name = forgery_py.lorem_ipsum.word(),
                        tags = forgery_py.lorem_ipsum.word() + "," + forgery_py.lorem_ipsum.word(),
                        description = forgery_py.lorem_ipsum.sentence(),
                        date = forgery_py.date.date(True),
                        links = forgery_py.lorem_ipsum.word(),
                        user_id = u.id)

            db.session.add(p)
            try:
                db.session.commit()
            except:
                db.session.rollback()



    def __repr__(self):
        return '<Project %r>' % self.name

class User(db.Model):
    __tablename__= 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(20), unique = True, index = True)
    password = db.Column(db.String(500))
    email = db.Column(db.String(50), unique = True)
    last_logged_in = db.Column(db.DateTime(), default=datetime.utcnow)
    projects = db.relationship('Project', backref='author', lazy='dynamic')

    @property
    def is_active(self):
        return True

    # @property
    # def password(self):
    #    raise AttributeError('Password is not a readable attritbute')

    def ping(self):
        self.last_logged_in = datetime.utcnow()
        db.session.add(self)
        db.session.commit()

    def get_id(self):
        try:
            return unicode(self.id)
        except NameError:
            return str(self.id)

    @property
    def is_authenticated(self):
            return True

    @property
    def is_anonymous(self):
            return False

    def authentication(self, input_password):
    	return sha256_crypt.verify(input_password, self.password)

    def set_password(self, input_password):
    	self.password = sha256_crypt.encrypt((input_password))

    def generate_fake(count = 20):
        from sqlalchemy.exc import IntegrityError
        from random import seed
        import forgery_py

        seed()
        user_count = User.query.count()
        for i in range(count):
            u = User(username = forgery_py.internet.user_name(True),
                     email = forgery_py.internet.email_address(),
                     last_logged_in = forgery_py.date.date(True))
            db.session.add(u)
            try:
                db.session.commit()
            except:
                db.session.rollback()

    def __repr__(self):
        return '<User %r>' % (self.username)

FlaskApp/forms.py
from wtforms import BooleanField, StringField, PasswordField, FileField, ValidationError, TextAreaField, validators
from flask_wtf import FlaskForm
from .models import User, Project
from wtforms.validators import Required, Length, EqualTo, regexp
from flask_wtf.file import FileAllowed
from FlaskApp import docs
import re

class LoginForm(FlaskForm):
    username = StringField('Username', [validators.Length(min=4, max=20)])
    password = PasswordField('Password', [validators.Required()])


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[Required(), Length(4, 20)])
    email = StringField('Email Address', validators=[Length(15,64)])
    password = PasswordField('Password', [validators.Required(),
                                          validators.EqualTo('confirm', message="Passwords must match")])
    confirm = PasswordField('Repeat Password')
    accept_tos = BooleanField('I Accept the Terms of Service...blablablabla', [validators.Required()])

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already taken')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already taken')

class EditForm(FlaskForm):
    username = StringField('Username', validators=[Length(4, 20)])
    email = StringField('Email Address', validators=[Length(6,50)])
    password = PasswordField('Password', validators=[EqualTo('confirm', message="passwords must match")])
    confirm = PasswordField('Repeat Password')

    def __init__(self, original_username, original_email, *args, **kwargs):
        FlaskForm.__init__(self, *args, **kwargs)
        self.original_username = original_username
        self.original_email = original_email

    def validate(self):
        if not FlaskForm.validate(self):
            return False
        if self.username.data == self.original_username and self.email.data == self.original_email:
            return True
        user = User.query.filter_by(username = self.username.data).first()
        if user != None:
           self.username.errors.append('Username already taken, choose another one')
           return False
        user = User.query.filter_by(email = self.email.data).first()
        if user != None:
            self.email.errors.append('Email already taken, choose another one')
            return False
        return True

class ProjectForm(FlaskForm):
    name = StringField('Name', validators=[Length(1, 50)])
    tags = StringField('Tags', validators=[Length(1, 200)])
    description = TextAreaField('Description', validators=[Required()])
    links = StringField('Links', validators=[Required()])
    document = FileField(u'Document file', validators=[FileAllowed(docs, 'Documents only')])

    def validate_name(self, field):
        if Project.query.filter_by(name = field.data):
            raise ValidationError('Name already taken')

class EditProjectForm(FlaskForm):
    name = StringField('Name', validators=[Length(1, 50)])
    tags = StringField('Tags', validators=[Length(1, 200)])
    description = TextFieldArea('Description', validators=[Required()])
    links = StringField('Links', validators=[Required()])
    document = FileField(u'Document file', validators=[FileAllowed(docs, 'Documents only')])

    def validate_name(self, field):
        if Project.query.filter_by(name = field.data):
            raise ValidationError('Name already taken')
    

    # def validate_document(form, field):
    #     if field.data:
    #         field.data = re.sub(r'[^a-z0-9_.-]', '_', field.data)

    def validate_name(self, field):
        if Project.query.filter_by(name = field.data).first():
            raise ValidationError('Project with this name already exists')

FlaskApp/__init__.py
from flask import Flask, Blueprint
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config
from flask_moment import Moment
from flask_uploads import UploadSet, DOCUMENTS, configure_uploads


app = Flask(__name__)
lm = LoginManager()
moment = Moment()
bootstrap = Bootstrap()
db = SQLAlchemy()
docs = UploadSet('documents', DOCUMENTS)

main = Blueprint('main', __name__)
from . import views, errors


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    lm.init_app(app)
    moment.init_app(app)
    configure_uploads(app, docs)
    lm.login_view = 'main.login_page'

    from . import main as main_blueprint

    app.register_blueprint(main_blueprint)

    return app

FlaskApp/views.py
from . import app, db, lm, docs
from flask import render_template, redirect, flash, url_for, request, g, session
from flask_login import login_user, logout_user, current_user, login_required
from .models import User, Project
from .forms import LoginForm, RegistrationForm, EditForm, ProjectForm
from . import main
from datetime import datetime
from sqlalchemy import desc



@main.context_processor
def inject_moment():
    return {'now': datetime.utcnow()}

@lm.user_loader
def user_loader(id):
    return User.query.get(int(id))

# @main.before_app_request
# def before_request():
#     g.user = current_user

@main.route('/')
@main.route('/homepage/')
def homepage():
        return render_template("main.html")

@main.app_errorhandler(404)
def page_not_found(e):
     return render_template("404.html")


@main.route('/dashboard/')
def dashboard():
    projects = Project.query.order_by(desc(Project.date))
    return render_template("dashboard.html", projects = projects)


@main.route('/login/', methods= ["GET", "POST"])
def login_page():
    error = ''
    form = LoginForm()
    try:
        if form.validate_on_submit():
            user = User.query.filter_by(username = form.username.data).first()
            if user:
                if user.authentication(str(form.password.data)):
                    login_user(user)
                    user.ping()
                    flash("You are now logged in")
                    return redirect(request.args.get('next') or url_for('main.dashboard'))
                else:
                    error = "Invalid Password, try again"
                    return render_template("login.html", login_form = form, error = error)
            else:
                error = "Username does not exist"
                return render_template("login.html", login_form = form, error = error)
        return render_template("login.html", login_form = form, error = error)

    except Exception as e:
        error = "Something is wrong"
        return render_template("login.html", login_form = form, error = error)


@main.route('/register/', methods=['GET', 'POST'])
def register_page():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()
        if user:
            error = "Username already taken"
            return render_template('register.html', form = form, error = error)
        else:
            new_user = User(username = form.username.data, email = form.email.data)
            new_user.set_password(str(form.password.data))
            new_user.ping()
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            flash('Registration succesful, you are now logged in')
            return redirect(url_for('main.dashboard'))

    return render_template('register.html', form = form)

@main.route('/dashboard/newproject', methods=['GET', 'POST'])
@login_required
def new_project():
    form = ProjectForm()
    if form.validate_on_submit():
        filename = docs.save(request.files['document'])
        url = docs.url(filename)
        project = Project(name = form.name.data, tags = form.tags.data,
                          description = form.description.data, links = form.links.data,
                           user_id = current_user.id, date = datetime.utcnow(),
                           image_filename=filename, image_url = url)
        db.session.add(project)
        db.session.commit()
        flash('Project added succesfully')
        return redirect(url_for('main.dashboard'))

    return render_template('newproject.html', form = form)

@main.route('/dashboard/project/<id>')
@login_required
def project(id):
    project = Project.query.get(id)
    return render_template('project.html', project = project)

@main.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first()
    if user==None:
        return redirect(url_for('main.homepage'))
    form = EditForm(user.username, user.email)
    form.username.data = user.username
    form.email.data = user.email

    return render_template('user.html', user=user, form=form)

@main.route('/edit/', methods = ['GET', 'POST'])
@login_required
def edit():
    form = EditForm(current_user.username, current_user.email)
    user = User.query.filter_by(username = current_user.username).first()
    if form.validate_on_submit():
        if user.validate_username(form.username) == ValidationError:
            flash('Username already taken')
        else:
            user.username = form.username.data
            user.email = form.email.data
        if form.password.data is not None:
            user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Your changes have been made')
        return redirect(url_for('main.edit'))
    else:
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('edit.html', form=form, user=user)

@main.route('/logout/')
def logout_page():
    logout_user()
    flash('You are now logged out')
    return redirect(url_for('main.homepage'))

FlaskApp/templates/_formhelpers.html
{% macro render_field(field) %}
	<dt>{{ field.label }}
	<dd>{{ field(**kwargs)|safe}}
	{% if field.errors %}
		<ul class=errors>
		{% for error in field.errors %}
			<li>{{ error }}</li>
		{% endfor %}
		</ul>
	{% endif %}
	</dd>
{% endmacro %}

FlaskApp/templates/dashboard.html
{% extends "template.html" %}

{% block page_content %}
<div class="col-md-8 col-md-offset-2" id="medContent">
	<ul class ="nav nav-tabs">
		<li role="presentation" name="panel1" data-toggle="tab"><a href="#">Information</a></li>
		<li role="presentation" class="active" name="panel2" data-toggle="tab"><a href="#">List of Projects</a></li>
		<li role="presentation" name="panel3" data-toggle="tab"><a href="#">Details</a></li>
		<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filters<span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><label><input type="checkbox" value="" />Option 1</label></li>
				<li><label><input type="checkbox" value="" />Option 2</label></li>
				<li><label><input type="checkbox" value="" />Option 3</label></li>
			</ul>
		</li>
</ul>




<div class="tab-content" id="tabs">
	<div class="tab-pane" id="panel1" name="1">
	<h3>About the projects</h3>
	<p>
		All the projects are listed under the "List of Projects"-tab. Most of the projects are from different assignments for MAH University.
		Mandatory to submit a project is a description, tags and a link to the github project. Without this you wont be able to submit a project.
		The reason is without this the project will be lacking too information for someone else to grasp what they project / assignment is about.
	</p>
	<h3>How do I contribute?</h3>
	<p>
		In order to submit a new project all you need is an account. In the top left corner press "Sign up" and create an account. After that
		a "Create new project" button will appear under List of Projects
	</p>

	</div>
	<div class="tab-pane active" id="panel2" name="2">
		<table class = "table table-hover">
			<thead>
				<th>Id</th>
				<th>Name</th>
				<th>Tags</th>
				<th>Submitted</th>
				<th>Author</th>
			</thead>
		<tbody>
			{% for project in projects %}
			<tr class>
				<td class="col-md-2"><a href= "{{ url_for('main.project', id = project.id) }}">{{ project.id }}</a></td>
				<td class="col-md-2">{{ project.name }}</td>
				<td class="col-md-6">{{ project.tags }}</td>
				<td class="col-md-2"><p> {{ moment(project.date).format('LL') }} </p></td>
				<td>{{ project.author.username }}</td>
			</tr>
			{% endfor %}
		</tbody>
		</table>
		<a class="btn btn-primary" href="{{ url_for('main.new_project') }}">Submit new project</a>

	</div>
	<div class="tab-pane" id="panel3" name="3"> Content3 </div>

</div>

	<div class="row">

		<div class="col-md-6">

		</div>


		<div class="col-md-6">


		</div>

	</div>
</div>
{% endblock %}

FlaskApp/templates/edit.html
{% extends "template.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

	<h4>{{ current_user.username }}</h4>
	<form method=post action="/edit/">
		{{ form.hidden_tag() }}
		<dl>
			{{wtf.form_field(form.username)}}
			{{wtf.form_field(form.email)}}
			{{wtf.form_field(form.password)}}
			{{wtf.form_field(form.confirm)}}
		</dl>
		<p><input class = "btn btn-primary" input type=submit value=Update></p>
		<p><a class="btn btn-danger" href="{{ url_for('main.user', username = current_user.username) }}">Cancel </a></p>
	</form>



{% endblock %}

FlaskApp/templates/footer.html
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="span8 offset2">
        <hr>
        <p><strong> &copy 2013 Add your footer. </strong></p>
      </div>
    </div> <!-- row -->
  </div> <!-- containter -->
</div> <!-- footer -->

FlaskApp/templates/header.html
<!DOCTYPE html>

<html lang="en">

<head>
	<meta charset="utf-8">
	<title> Arduino Projects example webpage </title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/customstyles.css') }}" rel="stylesheet">

<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">


</head>
<header>


<nav class="navbar navbar-inverse">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-header">
				<a class="navbar-brand" href="/"> Anton Hellbe </a>
		</div>
		<ul class="nav navbar-nav">
			<li class="active"> <a href="/">Hem</a></li>
			<li class="active"> <a href="/">Projekt</a></li>
			<li class="active"> <a href="/">Övrigt</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			{% if session.logged_in %}
				<li> <a href="#"><span class ="glyphicon glyphicon-user"></span> {{ session.username }} </a></li>
				<li><a href="/logout/"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
			{% else %}
				<li><a href="/register/"><span class="glyphicon glyphicon-user"> </span> Sign Up </a></li>
				<li><a href="/login/"><span class="glyphicon glyphicon-log-in"></span> Login </a></li>
			{% endif %}

		</ul>
	</nav>
</div>


</header>
<body>

<div class="border-row" style="width:100%; margin-bottom: 15px;"></div>

<div class=container>
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

    </div>

    {% endfor %}
  {% endif %}
{% endwith %}

 
{% block body %}
{% endblock %}

</div>

<footer class="footer">
	<div class="container">

		<div class="row">

			</div>

			<div class="col-md-6 col-sm-12 col-xs-12">
			<ul class="list-unstyled">
				<li><a class="black-text" href="https://www.hitta.se/anton+hellbe/malm%C3%B6/person/iVTRZsw-4v"> Anton Hellbe</a></li>
				<li><a class="black-text" > Krutmeijersgatan 16A </a></li>
				<li><a class="black-text"> Malmö, 21741 </a></li>

			</ul>

			</div>
			<div class="col-md-6 col-sm-12 col-xs-12">
				<ul class="list-unstyled">
				<li><a class="black-text" href="https://www.facebook.com/HEJHEJHEJHEJ"> Facebook </a></li>
				<li><a class="black-text" href="https://www.facebook.com/HEJHEJHEJHEJ"> Twitter </a></li>
				<li><a class="black-text" href="https://www.facebook.com/HEJHEJHEJHEJ"> Google </a></li>
				</ul>

			</div>
		</div>
		
	</div>
</footer>



<script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

</body>














</html>

FlaskApp/templates/login.html
{% extends "template.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

<div class="col-md-8 col-md-offset-2" id="medContent">
	<h4> Please Login</h4>
	<form method="post" action="/login/">
		<dl>
			{{ login_form.hidden_tag() }}
			{{wtf.form_field(login_form.username)}}
			{{wtf.form_field(login_form.password)}}
		</dl>
	<p><input class = "btn btn-primary" input type=submit value=Login></p>
	</form>
	{% if error %}
		<p class="error"><strong> {{ error }} </strong></p>
	{% endif %}
</div>

{% endblock %}

FlaskApp/templates/logout.html
{% extends "template.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<body>

<div class="container">

	<h4> Please Login</h4>

		<form method="POST" action="/login/">
			<dl>
			{{ form.hidden_tag() }}
			{{ wtf.form_field(login_form.username) }}
			{{ wtf.form_field(login_form.password) }}
			</dl>
			<p><input class = "btn btn-primary" input type=submit value=Login></p>
		</form>

		{% if error %}

		<p class="error">{{ error }}</p>

		{% endif %}

</div>


</body>

{% endblock %}

FlaskApp/templates/main.html
{% extends "template.html" %}


{% block jumbotron %}

<div class="jumbotron">
	<div class="container">
		<h1>MAH - Labs and Assignments</h1>
	 	<p>This page is mainly created to learn Pythonflask and Bootstrap. But it might create some inspiration for other people to take up fun arduino projects. Enjoy!</p>
	  	<p><a class="btn btn-primary btn-lg" href="/dashboard/" role="button">Learn more</a></p>
	</div>
</div>

{% endblock %}

{% block page_content %}
	<div class="row">
		<div class="col-md-4">
		<p> This is an example where accelerometer data is plotted with matlab </p>
		<div class="embed-responsive embed-responsive-16by9">
			<iframe class="embed-responsive-item" src="http://www.youtube.com/embed/ihfdMLCnKEU"> </iframe>
		</div>
		<p><a class="btn btn-default" href="#" role="button" style="margin-top: 5px;">Learn More &raquo;</a></p>
		</div>
		<div class="col-md-4">
			<p>Controlling a lift with arduino due and Matlab. How it works is explained in the video</p>
			<div class="embed-responsive embed-responsive-16by9">
			<iframe class="embed-responsive-item" src="http://www.youtube.com/embed/hWVskcvoCIk"> </iframe>
			</div>
			<p><a class="btn btn-default" href="#" role="button" style="margin-top: 5px;">Learn More &raquo;</a></p>
		</div>
		<div class="col-md-4">
			<p>Opening a codelock with arduino due and Matlab. Code is programmable, how it works is explained in the video.</p>
			<div class="embed-responsive embed-responsive-16by9">
			<iframe class="embed-responsive-item" src="http://www.youtube.com/embed/6UJABRN455o"> </iframe>
		</div>
		<p><a class="btn btn-default" href="#" role="button" style="margin-top: 5px;">Learn More &raquo;</a></p>
		</div>
	</div>

	<div class="row">
		<div class="col-md-4">
			<p> This is an example where accelerometer data is plotted with matlab </p>
			<div class="embed-responsive embed-responsive-16by9">
			<iframe class="embed-responsive-item" src="http://www.youtube.com/embed/hWVskcvoCIk"> </iframe>
			</div>
			<p><a class="btn btn-default" href="#" role="button" style="margin-top: 5px;">Learn More &raquo;</a></p>
		</div>
	</div>


{% endblock %}







</html>

FlaskApp/templates/newproject.html
{% extends "template.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

<div class="col-md-8 col-md-offset-2" id="medContent">

<form method=post action="/dashboard/newproject" enctype="multipart/form-data">
  <dl>
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.name) }}
    {{ wtf.form_field(form.tags) }}
    {{ wtf.form_field(form.description) }}
    {{ wtf.form_field(form.links) }}
    {{ wtf.form_field(form.document)}}
  </dl>
  <p><input class="btn btn-primary" input type="submit" value="Submit project"></p>
</form>

</div>

{% endblock %}

FlaskApp/templates/register.html
{% extends "template.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="col-md-8 col-md-offset-2" id="medContent">
	<h4>Register</h4>
	<br>
	<form method=post action="/register/">
	<dl>
		{{ form.hidden_tag() }}
		{{ wtf.form_field(form.username) }}
		{{ wtf.form_field(form.email) }}
		{{ wtf.form_field(form.password) }}
		{{ wtf.form_field(form.confirm) }}
		{{ wtf.form_field(form.accept_tos) }}
	</dl>
	<p><input class = "btn btn-primary" input type="submit" value=Register></p>
	</form>

	{% if error %}
		<p><strong> Error: </strong> {{ error }}</p>
	{% endif %}
</div>

{% endblock %}

FlaskApp/templates/template.html
{% extends "bootstrap/base.html" %}

{% block head %}
	{{ super() }}
	<meta charset="utf-8">
	<title> Arduino Projects example webpage </title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<link href="{{ url_for('static', filename='css/customstyles.css') }}" rel="stylesheet">
	<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

{% endblock %}

<body>

{% block navbar %}

<nav class="navbar navbar-inverse">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-header">
				<a class="navbar-brand" href="/"> MAH - Labs </a>
		</div>
		<ul class="nav navbar-nav">
			<li class="active"> <a href="/">Hem</a></li>
			<li class="active"> <a href="{{ url_for('main.dashboard') }}">Projekt</a></li>
			<li class="active"> <a href="/">Övrigt</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			{% if current_user.is_authenticated %}
				<li> <a href="{{ url_for('main.user', username = current_user.username) }}"><span class ="glyphicon glyphicon-user"></span> {{ current_user.username }} </a></li>
				<li><a href="{{ url_for('main.logout_page') }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
			{% else %}
				<li><a href="{{ url_for('main.register_page')}}"><span class="glyphicon glyphicon-user"> </span> Sign Up </a></li>
				<li><a href="{{ url_for('main.login_page')}}"><span class="glyphicon glyphicon-log-in"></span> Login </a></li>
			{% endif %}
		</ul>
	</nav>
</div>

{% endblock %}



{% block content %}

{% block jumbotron %}{% endblock %}

<div class ="border-row" style="width: 100%; margin-bottom: 15px;"> </div>

<div class="container">
	{% with messages = get_flashed_messages() %}
	  {% if messages %}
	    {% for message in messages %}
	    	<div class="alert alert-warning alert-dismissible" role="alert">
	    	{{message}}
	    	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	    </div>
	    {% endfor %}
	  {% endif %}
	{% endwith %}
</div>



<div class="container" style="min-height: 100%;" id="content">
		{% block page_content %}{% endblock %}
</div>

{% block footer %}
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-md-offset-2">
				<ul class="list-unstyled">
					<li><a class="black-text" href="#"> Anton Hellbe</a></li>
					<li><a class="black-text" href="#"> Krutmeijersgatan 16A </a></li>
					<li><a class="black-text" href="#"> Malmö, 21741 </a></li>
				</ul>
			</div>
			<div class="col-md-4 col-md-offset-2">
				<ul class="list-unstyled">
				<li><a class="black-text" href="https://www.facebook.com/HEJHEJHEJHEJ"> Facebook </a></li>
				<li><a class="black-text" href="#"> Twitter </a></li>
				<li><a class="black-text" href="#"> Google </a></li>
				</ul>
			</div>
		</div>
	</div>
</footer>


{% endblock %}

{% endblock %}




{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ moment.locale('sv')}}
<script>
	$(function() {
		$('#medContent li[role="presentation"]').on('click', function() {
			var $panel = $(this).closest('.container');
			$panel.find('li.active').removeClass('active');
			$(this).addClass('active');
			var panelToShow = $(this).attr('name');

			$panel.find('.tab-pane.active').slideUp(300, showNextPanel);
			function showNextPanel() {
				$(this).removeClass('active');

				$('#' + panelToShow).slideDown(300, function() {
					$(this).addClass('active');
				});
			}
		});
	});
</script>
{% endblock %}

</body>